services:
  nginx:
    image: ${DOCKER_USERNAME}/mernchess_frontend:latest
    container_name: mern_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/conf.d/prod.conf:/etc/nginx/conf.d/default.conf:ro
      - ./nginx/certs:/etc/nginx/certs:ro

    depends_on:
      - backend
    restart: always

  backend:
    image: ${DOCKER_USERNAME}/mernchess_backend:latest
    container_name: mern_backend
    # No need to expose 5000 to the host; Nginx talks to it internally
    expose:
      - "5000"
    env_file:
      - /root/mern_chess/.env
    restart: always
