services:
  backend:
    # This pulls the image your GitHub Action just built and pushed
    image: ${DOCKER_USERNAME}/mernchess_backend:latest
    ports:
      - "5000:5000"
    # This tells the container to use the .env file we create in the Master YAML
    env_file:
      - .env
    restart: always

  frontend:
    image: ${DOCKER_USERNAME}/mernchess_frontend:latest
    ports:
      - "80:80"
    restart: always
    depends_on:
      - backend
